[Release] 3.2.2 (#382)
* init patch

* Feature/lit 2570 js sdk fix build (#387)

* feat: make capacityTokenId optional

* chore: add test

* fix: Conditionally include nft_id

* fix: replace nx executor to @nrwl/js:tsc

* fix: replace nx executor

* feat: migrated nx to 15.9.0

* feat: migration nx from 15.9.0 -> 16.10.0

* feat: migrate nx to 17.3.0

* fix: yarn:test:unit command

* chore: log cc nft token info

* fix: undefined typings in package.json

* remove old v0 errors from js sdk.  provide error details to the user (#385)

* remove old v0 errors from js sdk.  provide error details to the user

* building now seems to consistently work

* refactored error handling to make it cleaner

* Remove unused function

* okay also added requestId in a few places

* ran the linter

* fix: replace nx executor

* feat: add gitignore

---------

Co-authored-by: Ansonhkg <ansonox@gmail.com>

* feat: cache enabled

* chore: update .gitignore

* chore: enable parallel

* feat: make capacityTokenId optional (#384)

* feat: make capacityTokenId optional

* chore: add test

* fix: Conditionally include nft_id

* Update yarn.lock to match package.json changes

* fix: ReferenceError: crypto is not defined

* fix: ignore nx cache directory on linting

* fix: ignore tools directory on linting

* fix: linting

* fix: '
ReferenceError: require is not defined in ES module scope, you can use import instead'

* fix: lint

* [Release] 3.2.2

* chore: move to manual tests

---------

Co-authored-by: Chris Cassano <1285652+glitch003@users.noreply.github.com>